version: '3'
services:

  # the db container is used by the silauth module
  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: r00tp@ss!
      MYSQL_DATABASE: silauth
      MYSQL_USER: silauth
      MYSQL_PASSWORD: silauth

  app:
    build: .
    depends_on:
      - ssp-hub.local
      - ssp-idp1.local
      - ssp-idp2.local
      - ssp-sp1.local
      - pwmanager.local
      - test-browser
    environment:
      - PROFILE_URL_FOR_TESTS=http://pwmanager.local/module.php/core/authenticate.php?as=ssp-hub
      - ADMIN_EMAIL=john_doe@there.com
      - ADMIN_PASS=b
      - SECRET_SALT=abc123
      - IDP_NAME=x
    volumes:
      - ./dockerbuild/run-integration-tests.sh:/data/run-integration-tests.sh
      - ./dockerbuild/run-metadata-tests.sh:/data/run-metadata-tests.sh
      - ./dockerbuild/run-tests.sh:/data/run-tests.sh
      - ./features:/data/features
      - ./behat.yml:/data/behat.yml
      - ./tests:/data/tests

  test-browser:
    image: justinribeiro/chrome-headless:stable
    cap_add:
      - SYS_ADMIN

  ssp-hub.local:
    build: .
    volumes:
      # Utilize custom certs
      - ./development/hub/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/hub/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php

      # Utilize custom metadata
      - ./development/hub/metadata/idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/idp-remote.php
      - ./development/hub/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/hub/metadata/saml20-sp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-hosted.php
      - ./development/hub/metadata/sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/sp-remote.php

      # Enable checking our test metadata
      - ./dockerbuild/run-metadata-tests.sh:/data/run-metadata-tests.sh
    command: /data/run.sh
    environment:
      ADMIN_EMAIL: "john_doe@there.com"
      ADMIN_PASS: "abc123"
      SECRET_SALT: "not-secret-h57fjemb&dn^nsJFGNjweJ"
      IDP_NAME: "Hub"
      SECURE_COOKIE: "false"
      ADMIN_PROTECT_INDEX_PAGE: "false"
      SHOW_SAML_ERRORS: "true"
      THEME_USE: "material:material"
      THEME_COLOR_SCHEME: "orange-light_blue"
      HUB_MODE: "true"

  ssp-idp1.local:
    build: .
    volumes:
      # Utilize custom certs
      - ./development/idp-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/idp-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      - ./development/idp-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php

      # Utilize custom metadata
      - ./development/idp-local/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/idp-local/metadata/saml20-sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-remote.php

      # Misc. files needed
      - ./development/enable-exampleauth-module.sh:/data/enable-exampleauth-module.sh

      # Customized SSP code -- TODO: make a better solution that doesn't require hacking SSP code
      - ./development/idp-local/UserPass.php:/data/vendor/simplesamlphp/simplesamlphp/modules/exampleauth/lib/Auth/Source/UserPass.php

      # Enable checking our test metadata
      - ./dockerbuild/run-metadata-tests.sh:/data/run-metadata-tests.sh

      # Include the features folder (for the FakeIdBrokerClient class)
      - ./features:/data/features
    command: 'bash -c "/data/enable-exampleauth-module.sh && /data/run.sh"'
    environment:
      ADMIN_EMAIL: "john_doe@there.com"
      ADMIN_PASS: "a"
      SECRET_SALT: "not-secret-h57fjemb&dn^nsJFGNjweJ"
      IDP_NAME: "IDP 1"
      IDP_DOMAIN_NAME: "mfaidp"
      ID_BROKER_ACCESS_TOKEN: "dummy"
      ID_BROKER_ASSERT_VALID_IP: "false"
      ID_BROKER_BASE_URI: "dummy"
      ID_BROKER_TRUSTED_IP_RANGES: "192.168.0.1/8"
      MFA_SETUP_URL: "http://pwmanager.local:8083/module.php/core/authenticate.php?as=ssp-hub-custom-port"
      REMEMBER_ME_SECRET: "12345"
      PROFILE_URL: "http://pwmanager:8083/module.php/core/authenticate.php?as=ssp-hub-custom-port"
      PROFILE_URL_FOR_TESTS: "http://pwmanager.local/module.php/core/authenticate.php?as=ssp-hub"
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"
      THEME_USE: "default"

  ssp-idp2.local:
    build: .
    volumes:
      # Utilize custom certs
      - ./development/idp2-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert  

      # Utilize custom configs
      - ./development/idp2-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      - ./development/idp2-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php

      # Utilize custom metadata
      - ./development/idp2-local/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/idp2-local/metadata/saml20-sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-remote.php

      # Local modules
      - ./modules/expirychecker:/data/vendor/simplesamlphp/simplesamlphp/modules/expirychecker
      - ./modules/profilereview:/data/vendor/simplesamlphp/simplesamlphp/modules/profilereview
    command: /data/run.sh
    ports:
      - "8086:80"
    environment:
      ADMIN_EMAIL: "john_doe@there.com"
      ADMIN_PASS: "b"
      SECRET_SALT: "h57fjemb&dn^nsJFGNjweJ"
      IDP_NAME: "IDP 2"
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"
      THEME_USE: "material:material"

  ssp-sp1.local:
    build: .
    volumes:
      # Utilize custom certs
      - ./development/sp-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/sp-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php
      - ./development/sp-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php

      # Utilize custom metadata
      - ./development/sp-local/metadata/saml20-idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-remote.php

      # Enable checking our test metadata
      - ./dockerbuild/run-metadata-tests.sh:/data/run-metadata-tests.sh
    environment:
      ADMIN_EMAIL: "john_doe@there.com"
      ADMIN_PASS: "sp1"
      SECRET_SALT: "not-secret-h57fjemb&dn^nsJFGNjweJz1"
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"
      SAML20_IDP_ENABLE: "false"
      ADMIN_PROTECT_INDEX_PAGE: "false"

  pwmanager.local:
    image: silintl/ssp-base:develop
    volumes:
      # Utilize custom certs
      - ./development/sp-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/sp-local/config/authsources-pwmanager.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php

      # Utilize custom metadata
      - ./development/sp-local/metadata/saml20-idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-remote.php
    environment:
      - ADMIN_EMAIL=john_doe@there.com
      - ADMIN_PASS=sp1
      - IDP_NAME=THIS VARIABLE IS REQUIRED BUT PROBABLY NOT USED
      - SECRET_SALT=NOT-a-secret-k49fjfkw73hjf9t87wjiw
      - SECURE_COOKIE=false
      - SHOW_SAML_ERRORS=true
      - SAML20_IDP_ENABLE=false
      - ADMIN_PROTECT_INDEX_PAGE=false
      - THEME_USE=default

  # the broker and brokerDb containers are used by the silauth module
  broker:
    image: silintl/idp-id-broker:latest
    ports:
      - "80"
    depends_on:
      - brokerDb
    environment:
      IDP_NAME: "idp"
      MYSQL_HOST: "brokerDb"
      MYSQL_DATABASE: "broker"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
      EMAIL_SERVICE_accessToken: "dummy"
      EMAIL_SERVICE_assertValidIp: "false"
      EMAIL_SERVICE_baseUrl: "dummy"
      EMAILER_CLASS: Sil\SilIdBroker\Behat\Context\fakes\FakeEmailer
      HELP_CENTER_URL: "https://example.org/help"
      PASSWORD_FORGOT_URL: "https://example.org/forgot"
      PASSWORD_PROFILE_URL: "https://example.org/profile"
      SUPPORT_EMAIL: "support@example.org"
      EMAIL_SIGNATURE: "one red pill, please"
      API_ACCESS_KEYS: "test-cli-abc123"
      APP_ENV: "prod"
      MFA_TOTP_apiBaseUrl: not_needed_here
      MFA_TOTP_apiKey: not_needed_here
      MFA_TOTP_apiSecret: not_needed_here
      MFA_WEBAUTHN_apiBaseUrl: not_needed_here
      MFA_WEBAUTHN_apiKey: not_needed_here
      MFA_WEBAUTHN_apiSecret: not_needed_here
    command: "bash -c 'whenavail brokerDb 3306 60 ./yii migrate --interactive=0 && ./run.sh'"

  brokerDb:
    image: mariadb:10
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "r00tp@ss!"
      MYSQL_DATABASE: "broker"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
