version: '3'
services:

  # the db container is used by the silauth module
  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: r00tp@ss!
      MYSQL_DATABASE: silauth
      MYSQL_USER: silauth
      MYSQL_PASSWORD: silauth

  app:
    build: .
    depends_on:
      - ssp-hub.local
      - ssp-idp1.local
      - ssp-idp2.local
      - ssp-idp3.local
      - ssp-sp1.local
      - ssp-sp2.local
      - ssp-sp3.local
      - pwmanager.local
      - test-browser
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: silauth
      MYSQL_USER: silauth
      MYSQL_PASSWORD: silauth
      PROFILE_URL_FOR_TESTS: http://pwmanager.local/module.php/core/authenticate.php?as=ssp-hub
      ADMIN_EMAIL: john_doe@there.com
      ADMIN_PASS: b
      SECRET_SALT: abc123
      IDP_NAME: x
    volumes:
      - ./dockerbuild/run-integration-tests.sh:/data/run-integration-tests.sh
      - ./dockerbuild/run-metadata-tests.sh:/data/run-metadata-tests.sh
      - ./dockerbuild/run-tests.sh:/data/run-tests.sh
      - ./features:/data/features
      - ./behat.yml:/data/behat.yml
      - ./tests:/data/tests

  test-browser:
    image: justinribeiro/chrome-headless:stable
    cap_add:
      - SYS_ADMIN

  ssp-hub.local:
    build: .
    volumes:
      # Utilize custom certs
      - ./development/hub/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/hub/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php

      # Utilize custom metadata
      - ./development/hub/metadata/idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/idp-remote.php
      - ./development/hub/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/hub/metadata/saml20-sp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-hosted.php
      - ./development/hub/metadata/sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/sp-remote.php

      # Enable checking our test metadata
      - ./dockerbuild/run-metadata-tests.sh:/data/run-metadata-tests.sh
    environment:
      ADMIN_EMAIL: "john_doe@there.com"
      ADMIN_PASS: "abc123"
      SECRET_SALT: "not-secret-h57fjemb&dn^nsJFGNjweJ"
      IDP_NAME: "Hub"
      SECURE_COOKIE: "false"
      ADMIN_PROTECT_INDEX_PAGE: "false"
      SHOW_SAML_ERRORS: "true"
      THEME_COLOR_SCHEME: "orange-light_blue"
      HUB_MODE: "true"

  ssp-idp1.local:
    build: .
    depends_on:
      - db
    volumes:
      # Utilize custom certs
      - ./development/idp-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/idp-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      - ./development/idp-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php

      # Utilize custom metadata
      - ./development/idp-local/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/idp-local/metadata/saml20-sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-remote.php

      # Customized SSP code -- TODO: make a better solution that doesn't require hacking SSP code
      - ./development/UserPass.php:/data/vendor/simplesamlphp/simplesamlphp/modules/exampleauth/lib/Auth/Source/UserPass.php

      # Enable checking our test metadata
      - ./dockerbuild/run-metadata-tests.sh:/data/run-metadata-tests.sh

      # Include the features folder (for the FakeIdBrokerClient class)
      - ./features:/data/features
    command: >
      bash -c "whenavail db 3306 60 /data/vendor/simplesamlphp/simplesamlphp/modules/silauth/lib/Auth/Source/yii migrate --interactive=0 &&
      /data/run.sh"
    environment:
      ADMIN_EMAIL: "john_doe@there.com"
      ADMIN_PASS: "a"
      SECRET_SALT: "not-secret-h57fjemb&dn^nsJFGNjweJ"
      IDP_NAME: "IDP 1"
      IDP_DOMAIN_NAME: "mfaidp"
      ID_BROKER_ACCESS_TOKEN: "dummy"
      ID_BROKER_ASSERT_VALID_IP: "false"
      ID_BROKER_BASE_URI: "dummy"
      ID_BROKER_TRUSTED_IP_RANGES: "192.168.0.1/8"
      MFA_SETUP_URL: "http://pwmanager.local/module.php/core/authenticate.php?as=ssp-hub-custom-port"
      REMEMBER_ME_SECRET: "12345"
      PROFILE_URL: "http://pwmanager.local/module.php/core/authenticate.php?as=ssp-hub-custom-port"
      PROFILE_URL_FOR_TESTS: "http://pwmanager.local/module.php/core/authenticate.php?as=ssp-hub"
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"
      MYSQL_HOST: "db"
      MYSQL_DATABASE: "silauth"
      MYSQL_USER: "silauth"
      MYSQL_PASSWORD: "silauth"
      BASE_URL_PATH: "http://ssp-idp1.local/"

  ssp-idp2.local:
    build: .
    volumes:
      # Utilize custom certs
      - ./development/idp2-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert  

      # Utilize custom configs
      - ./development/idp2-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      - ./development/idp2-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php

      # Utilize custom metadata
      - ./development/idp2-local/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/idp2-local/metadata/saml20-sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-remote.php

      # Customized SSP code -- TODO: make a better solution that doesn't require hacking SSP code
      - ./development/UserPass.php:/data/vendor/simplesamlphp/simplesamlphp/modules/exampleauth/lib/Auth/Source/UserPass.php

    environment:
      ADMIN_EMAIL: "john_doe@there.com"
      ADMIN_PASS: "b"
      SECRET_SALT: "h57fjemb&dn^nsJFGNjweJ"
      IDP_NAME: "IDP 2"
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"

  ssp-idp3.local:
    build: .
    volumes:
      # Utilize custom certs
      - ./development/idp3-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/idp3-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      - ./development/idp3-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php

      # Utilize custom metadata
      - ./development/idp3-local/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/idp3-local/metadata/saml20-sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-remote.php

    environment:
      ADMIN_EMAIL: "john_doe@there.com"
      ADMIN_PASS: "c"
      SECRET_SALT: "h57fjem34fh*nsJFGNjweJ"
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"
      IDP_NAME: "IdP3"

  ssp-sp1.local:
    build: .
    volumes:
      # Utilize custom certs
      - ./development/sp-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/sp-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php
      - ./development/sp-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php

      # Utilize custom metadata
      - ./development/sp-local/metadata/saml20-idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-remote.php

      # Enable checking our test metadata
      - ./dockerbuild/run-metadata-tests.sh:/data/run-metadata-tests.sh
    environment:
      ADMIN_EMAIL: "john_doe@there.com"
      ADMIN_PASS: "sp1"
      SECRET_SALT: "not-secret-h57fjemb&dn^nsJFGNjweJz1"
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"
      SAML20_IDP_ENABLE: "false"
      ADMIN_PROTECT_INDEX_PAGE: "false"

  ssp-sp2.local:
    build: .
    volumes:
      # Utilize custom certs
      - ./development/sp2-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/sp2-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php
      - ./development/sp2-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php

      # Utilize custom metadata
      - ./development/sp2-local/metadata/saml20-idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-remote.php

    environment:
      ADMIN_EMAIL: john_doe@there.com
      ADMIN_PASS: sp2
      SECRET_SALT: h57fjemb&dn^nsJFGNjweJz2
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"
      SAML20_IDP_ENABLE: "false"
      ADMIN_PROTECT_INDEX_PAGE: "false"

  ssp-sp3.local:
    build: .
    volumes:
      # Utilize custom certs
      - ./development/sp3-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/sp3-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php
      - ./development/sp3-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php

      # Utilize custom metadata
      - ./development/sp3-local/metadata/saml20-idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-remote.php

    environment:
      ADMIN_EMAIL: john_doe@there.com
      ADMIN_PASS: sp3
      SECRET_SALT: h57fjemb&dn^nsJFGNjweJz3
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"
      SAML20_IDP_ENABLE: "false"
      ADMIN_PROTECT_INDEX_PAGE: "false"


  pwmanager.local:
    image: silintl/ssp-base:develop
    volumes:
      # Utilize custom certs
      - ./development/sp-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/sp-local/config/authsources-pwmanager.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php

      # Utilize custom metadata
      - ./development/sp-local/metadata/saml20-idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-remote.php
    environment:
      ADMIN_EMAIL: john_doe@there.com
      ADMIN_PASS: sp1
      IDP_NAME: THIS VARIABLE IS REQUIRED BUT PROBABLY NOT USED
      SECRET_SALT: NOT-a-secret-k49fjfkw73hjf9t87wjiw
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"
      SAML20_IDP_ENABLE: "false"
      ADMIN_PROTECT_INDEX_PAGE: "false"

  # the broker and brokerDb containers are used by the silauth module
  broker:
    image: silintl/idp-id-broker:latest
    depends_on:
      - brokerDb
    environment:
      IDP_NAME: "idp"
      MYSQL_HOST: "brokerDb"
      MYSQL_DATABASE: "broker"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
      EMAIL_SERVICE_accessToken: "dummy"
      EMAIL_SERVICE_assertValidIp: "false"
      EMAIL_SERVICE_baseUrl: "dummy"
      EMAILER_CLASS: Sil\SilIdBroker\Behat\Context\fakes\FakeEmailer
      HELP_CENTER_URL: "https://example.org/help"
      PASSWORD_FORGOT_URL: "https://example.org/forgot"
      PASSWORD_PROFILE_URL: "https://example.org/profile"
      SUPPORT_EMAIL: "support@example.org"
      EMAIL_SIGNATURE: "one red pill, please"
      API_ACCESS_KEYS: "test-cli-abc123"
      APP_ENV: "prod"
      MFA_TOTP_apiBaseUrl: not_needed_here
      MFA_TOTP_apiKey: not_needed_here
      MFA_TOTP_apiSecret: not_needed_here
      MFA_WEBAUTHN_apiBaseUrl: not_needed_here
      MFA_WEBAUTHN_apiKey: not_needed_here
      MFA_WEBAUTHN_apiSecret: not_needed_here
    command: "bash -c 'whenavail brokerDb 3306 60 ./yii migrate --interactive=0 && ./run.sh'"

  brokerDb:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: "r00tp@ss!"
      MYSQL_DATABASE: "broker"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
