version: '3'
services:
  app:
    build: .
    depends_on:
      - ssp-hub.local
      - ssp-idp1.local
      - ssp-idp2.local
      - ssp-sp1.local
      - test-browser
    environment:
      - PROFILE_URL_FOR_TESTS=http://ssp-sp1.local/module.php/core/authenticate.php?as=ssp-hub
    volumes:
      - ./dockerbuild/run-integration-tests.sh:/data/run-integration-tests.sh
      - ./dockerbuild/run-metadata-tests.sh:/data/run-metadata-tests.sh
      - ./dockerbuild/run-tests.sh:/data/run-tests.sh
      - ./features:/data/features
      - ./behat.yml:/data/behat.yml
      - ./tests:/data/tests

  test-browser:
    image: justinribeiro/chrome-headless:stable
    cap_add:
      - SYS_ADMIN

  ssp-hub.local:
    build: .
    volumes:
      # Utilize custom certs
      - ./development/hub/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/hub/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php

      # Utilize custom metadata
      - ./development/hub/metadata/idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/idp-remote.php
      - ./development/hub/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/hub/metadata/saml20-sp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-hosted.php
      - ./development/hub/metadata/sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/sp-remote.php

      # Enable checking our test metadata
      - ./dockerbuild/run-metadata-tests.sh:/data/run-metadata-tests.sh
    command: /data/run.sh
    environment:
      ADMIN_EMAIL: "john_doe@there.com"
      ADMIN_PASS: "abc123"
      SECRET_SALT: "not-secret-h57fjemb&dn^nsJFGNjweJ"
      IDP_NAME: "Hub"
      SECURE_COOKIE: "false"
      ADMIN_PROTECT_INDEX_PAGE: "false"
      SHOW_SAML_ERRORS: "true"
      THEME_USE: "material:material"
      THEME_COLOR_SCHEME: "orange-light_blue"
      HUB_MODE: "true"

  ssp-idp1.local:
    build: .
    volumes:
      # Utilize custom certs
      - ./development/idp-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/idp-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      - ./development/idp-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php

      # Utilize custom metadata
      - ./development/idp-local/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/idp-local/metadata/saml20-sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-remote.php

      # Misc. files needed
      - ./development/enable-exampleauth-module.sh:/data/enable-exampleauth-module.sh

      # Customized SSP code -- TODO: make a better solution that doesn't require hacking SSP code
      - ./development/idp-local/UserPass.php:/data/vendor/simplesamlphp/simplesamlphp/modules/exampleauth/lib/Auth/Source/UserPass.php

      # Enable checking our test metadata
      - ./dockerbuild/run-metadata-tests.sh:/data/run-metadata-tests.sh
    command: 'bash -c "/data/enable-exampleauth-module.sh && /data/run.sh"'
    environment:
      ADMIN_EMAIL: "john_doe@there.com"
      ADMIN_PASS: "a"
      SECRET_SALT: "not-secret-h57fjemb&dn^nsJFGNjweJ"
      IDP_NAME: "IDP 1"
      PROFILE_URL: "http://ssp-hub-sp1:8083/module.php/core/authenticate.php?as=ssp-hub-custom-port"
      PROFILE_URL_FOR_TESTS: "http://ssp-sp1.local/module.php/core/authenticate.php?as=ssp-hub"
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"
      THEME_USE: "default"

  ssp-idp2.local:
    build: .
    volumes:
      # Utilize custom certs
      - ./development/idp2-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert  

      # Utilize custom configs
      - ./development/idp2-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      - ./development/idp2-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php

      # Utilize custom metadata
      - ./development/idp2-local/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/idp2-local/metadata/saml20-sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-remote.php

      # Local modules
      - ./modules/expirychecker:/data/vendor/simplesamlphp/simplesamlphp/modules/expirychecker
      - ./modules/profilereview:/data/vendor/simplesamlphp/simplesamlphp/modules/profilereview
    command: /data/run.sh
    ports:
      - "8086:80"
    environment:
      ADMIN_EMAIL: "john_doe@there.com"
      ADMIN_PASS: "b"
      SECRET_SALT: "h57fjemb&dn^nsJFGNjweJ"
      IDP_NAME: "IDP 2"
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"
      THEME_USE: "material:material"

  ssp-sp1.local:
    build: .
    volumes:
      # Utilize custom certs
      - ./development/sp-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/sp-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php
      - ./development/sp-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php

      # Utilize custom metadata
      - ./development/sp-local/metadata/saml20-idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-remote.php

      # Enable checking our test metadata
      - ./dockerbuild/run-metadata-tests.sh:/data/run-metadata-tests.sh
    environment:
      ADMIN_EMAIL: "john_doe@there.com"
      ADMIN_PASS: "sp1"
      SECRET_SALT: "not-secret-h57fjemb&dn^nsJFGNjweJz1"
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"
      SAML20_IDP_ENABLE: "false"
      ADMIN_PROTECT_INDEX_PAGE: "false"
