version: "2"
services:
  ssp:
    build: .
    volumes:
      # Utilize custom certs
      - ./development/ssp/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/ssp/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      
      # Configure the debugger
      - ./development/ssp/run-debug.sh:/data/run-debug.sh

      # Local modules
      - ./modules/expirychecker:/data/vendor/simplesamlphp/simplesamlphp/modules/expirychecker
      - ./modules/profilereview:/data/vendor/simplesamlphp/simplesamlphp/modules/profilereview

    command: ["/data/run-debug.sh"]
    ports:
      - "80:80"
    env_file:
      - ./local.env

  db:
    image: mariadb:10
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: r00tp@ss!
      MYSQL_DATABASE: silauth
      MYSQL_USER: silauth
      MYSQL_PASSWORD: silauth

  test:
    build: .
    depends_on:
      - ssp-hub.local
      - ssp-idp1.local
      - ssp-sp1.local
      - test-browser
    environment:
      - COMPOSER_CACHE_DIR=/composer
    volumes:
      - ./composer.json:/data/composer.json
      - ./composer.lock:/data/composer.lock
      - ${COMPOSER_CACHE_DIR}:/composer
      - ./dockerbuild/run-integration-tests.sh:/data/run-integration-tests.sh
      - ./dockerbuild/run-metadata-tests.sh:/data/run-metadata-tests.sh
      - ./dockerbuild/run-tests.sh:/data/run-tests.sh
      - ./dockerbuild/apply-dictionaries-overrides.php:/data/apply-dictionaries-overrides.php
      - ./features:/data/features
      - ./behat.yml:/data/behat.yml
      - ./tests:/data/tests
      - ./modules/expirychecker:/data/vendor/simplesamlphp/simplesamlphp/modules/expirychecker
      - ./modules/profilereview:/data/vendor/simplesamlphp/simplesamlphp/modules/profilereview
    command: ["/data/run-tests.sh"]

  test-browser:
    image: justinribeiro/chrome-headless:stable
    ports:
      - "9222:9222"
    cap_add:
      - SYS_ADMIN

  composer:
    build: .
    volumes:
      - ./composer.json:/data/composer.json
      - ./composer.lock:/data/composer.lock
      - ./installed-packages.json:/data/installed-packages.json
      - ./development/update-composer-deps.sh:/data/update-composer-deps.sh
      - ./vendor:/data/vendor
      - ${COMPOSER_CACHE_DIR}:/composer
    env_file:
      - ./local.env
    environment:
      - COMPOSER_CACHE_DIR=/composer

  ssp-hub.local:
    build: .
    volumes:
      # Utilize custom certs
      - ./development/hub/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/hub/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php

      # Utilize custom metadata
      - ./development/hub/metadata/idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/idp-remote.php
      - ./development/hub/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/hub/metadata/saml20-sp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-hosted.php
      - ./development/hub/metadata/sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/sp-remote.php

      # Configure the debugger
      - ./development/hub/run-debug.sh:/data/run-debug.sh

      # Enable checking our test metadata
      - ./dockerbuild/run-metadata-tests.sh:/data/run-metadata-tests.sh

      # Local modules
      - ./modules/expirychecker:/data/vendor/simplesamlphp/simplesamlphp/modules/expirychecker
      - ./modules/profilereview:/data/vendor/simplesamlphp/simplesamlphp/modules/profilereview
    command: /data/run-debug.sh
    ports:
      - "80:80"
    environment:
      ADMIN_EMAIL: "john_doe@there.com"
      ADMIN_PASS: "abc123"
      SECRET_SALT: "h57fjemb&dn^nsJFGNjweJ"
      IDP_NAME: "Hub"
      SECURE_COOKIE: "false"
      ADMIN_PROTECT_INDEX_PAGE: "false"
      SHOW_SAML_ERRORS: "true"
      THEME_USE: "material:material"
      THEME_COLOR_SCHEME: "orange-light_blue"
      HUB_MODE: "true"

  ssp-idp1.local:  # using a database session store type ("sql")
    build: .
    depends_on:
      - db
    volumes:
      # Utilize custom certs
      - ./development/idp-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert 

      # Utilize custom configs
      - ./development/idp-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      - ./development/idp-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php

      # Utilize custom metadata
      - ./development/idp-local/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/idp-local/metadata/saml20-sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-remote.php

      # Misc. files needed
      - ./development/enable-exampleauth-module.sh:/data/enable-exampleauth-module.sh

      # Enable checking our test metadata
      - ./dockerbuild/run-metadata-tests.sh:/data/run-metadata-tests.sh

      # Local modules
      - ./modules/expirychecker:/data/vendor/simplesamlphp/simplesamlphp/modules/expirychecker
      - ./modules/profilereview:/data/vendor/simplesamlphp/simplesamlphp/modules/profilereview
    command: 'bash -c "/data/enable-exampleauth-module.sh && /data/run.sh"'
    ports:
      - "8085:80"
    environment:
      ADMIN_EMAIL: "john_doe@there.com"
      ADMIN_PASS: "a"
      SECRET_SALT: "h57fjemb&dn^nsJFGNjweJ"
      IDP_NAME: "IDP 1"
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"
      THEME_USE: "material:material"
      SESSION_STORE_TYPE: "sql"
      MYSQL_HOST: "db"
      MYSQL_DATABASE: "silauth"
      MYSQL_USER: "silauth"
      MYSQL_PASSWORD: "silauth"

  idp2:
    build: .
    volumes:
      # Utilize custom certs
      - ./development/idp2-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert  

      # Utilize custom configs
      - ./development/idp2-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      - ./development/idp2-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php

      # Utilize custom metadata
      - ./development/idp2-local/metadata/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/idp2-local/metadata/saml20-sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-remote.php

      # Local modules
      - ./modules/expirychecker:/data/vendor/simplesamlphp/simplesamlphp/modules/expirychecker
      - ./modules/profilereview:/data/vendor/simplesamlphp/simplesamlphp/modules/profilereview
    command: /data/run.sh
    ports:
      - "8086:80"
    environment:
      ADMIN_EMAIL: "john_doe@there.com"
      ADMIN_PASS: "b"
      SECRET_SALT: "h57fjemb&dn^nsJFGNjweJ"
      IDP_NAME: "IDP 2"
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"

  ssp-sp1.local:
    build: .
    volumes:
      # Utilize custom certs
      - ./development/sp-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/sp-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php
      - ./development/sp-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php

      # Utilize custom metadata
      - ./development/sp-local/metadata/saml20-idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-remote.php

      # Enable checking our test metadata
      - ./dockerbuild/run-metadata-tests.sh:/data/run-metadata-tests.sh

      # Local modules
      - ./modules/expirychecker:/data/vendor/simplesamlphp/simplesamlphp/modules/expirychecker
      - ./modules/profilereview:/data/vendor/simplesamlphp/simplesamlphp/modules/profilereview
    ports:
      - "8081:80"
    environment:
      ADMIN_EMAIL: "john_doe@there.com"
      ADMIN_PASS: "sp1"
      SECRET_SALT: "h57fjemb&dn^nsJFGNjweJz1"
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"
      SAML20_IDP_ENABLE: "false"
      ADMIN_PROTECT_INDEX_PAGE: "false"

  sp2:
    build: .
    volumes:
      # Utilize custom certs
      - ./development/sp2-local/cert:/data/vendor/simplesamlphp/simplesamlphp/cert

      # Utilize custom configs
      - ./development/sp2-local/config/config.php:/data/vendor/simplesamlphp/simplesamlphp/config/config.php
      - ./development/sp2-local/config/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php

      # Utilize custom metadata
      - ./development/sp2-local/metadata/saml20-idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-remote.php

      # Local modules
      - ./modules/expirychecker:/data/vendor/simplesamlphp/simplesamlphp/modules/expirychecker
      - ./modules/profilereview:/data/vendor/simplesamlphp/simplesamlphp/modules/profilereview
    ports:
      - "8082:80"
    environment:
      ADMIN_EMAIL: "john_doe@there.com"
      ADMIN_PASS: "sp2"
      SECRET_SALT: "h57fjemb&dn^nsJFGNjweJz2"
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"
      SAML20_IDP_ENABLE: "false"
      ADMIN_PROTECT_INDEX_PAGE: "false"
    
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.20.38.0/24
          gateway: 10.20.38.1
