# Second listener alongside port 80 -- see docs/development.md "Why idp1/idp2/idp4 listen on two ports".
Listen 8086

<VirtualHost _default_:8086>
  DocumentRoot /data/vendor/simplesamlphp/simplesamlphp/public/
  RewriteEngine On
  DirectoryIndex index.php

  <Directory /data/vendor/simplesamlphp/simplesamlphp/public/>
    Options FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>

  LogLevel info
  CustomLog /var/log/apache2/access.log combined
</VirtualHost>
