name: Test and Publish

on:
  push:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create env files
        run: cp local.env.dist local.env && cp local.broker.env.dist local.broker.env
      - name: test
        run: docker compose run test ./run-tests.sh
      - name: check hub metadata for tests
        run: docker compose run ssp-hub.local ./run-metadata-tests.sh
      - name: check idp metadata for tests
        run: docker compose run ssp-idp1.local ./run-metadata-tests.sh
      - name: check sp metadata for tests
        run: docker compose run ssp-sp1.local ./run-metadata-tests.sh

  build-and-publish:
    name: Build and Publish Docker image
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        if: startsWith(github.ref, 'refs/tags')
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.DOCKER_ORG }}/${{ github.event.repository.name }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push Docker image to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GITHUB_REF_NAME=${{ github.ref_name }}
